name = "codecrafters_shell"
version = "1.0.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.36.0 and < 1.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
envoy = ">= 1.0.1 and < 1.1.0"
simplifile = ">= 2.3.1 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
party = ">= 1.0.6 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
